### ISSUE TITLE
Errors in README

### ISSUE THREAD

**Issue by a-shestakov** [cwilso/WebMIDIAPIShim#12]
The line in README

```
o.sendMessage( [ 0x90, 0x45, 0xff ] );
```

should be

```
o.send( [ 0x90, 0x45, 0x7f ] );
```

Because, according to specs (http://www.w3.org/TR/webmidi/#sending-midi-messages-to-an-output-device):
1. MIDIOutput's method to send messages is simply .send()
2. maximum velocity of a note is 127, not 255.

**Comment by cwilso** [comment]
Fixed.  Thanks!
