### ISSUE TITLE
Throw exception on spec change?

### ISSUE THREAD

**Issue by notator** [cwilso/WebMIDIAPIShim#13]
I'm using the WebMIDIAPIShim to keep my project up to date with the spec, so it would be helpful if you simply threw an exception when I'm using a name which no longer exists.
For example:

``` javascript
if (window.navigator.getMIDIAccess) {
    throw "Spec change: 'getMIDIAccess' has been renamed 'requestMIDIAccess'";
}
if (!window.navigator.requestMIDIAccess) {
    window.navigator.requestMIDIAccess = _requestMIDIAccess;
}

```

Could that be done?

**Comment by cwilso** [comment]
Instead of throwing, I started console.error()ing.

**Comment by cwilso** [comment]
Actually, I think it's console.warn, and I keep supporting the old version if possible.
