### ISSUE TITLE
More wider support with Flash/Java ?

### ISSUE THREAD

**Issue by nfroidure** [cwilso/WebMIDIAPIShim#34]
While surfing, i found the following libraries: 
- Flash http://wonderfl.net/c/4IH3
- JAVA https://github.com/abudaan/MIDIBridge

Just posting in case someone would like to use them to increase the polyfill browser/OS support.

**Comment by cwilso** [comment]
Hey Nicholas -

I actually used to use MIDIBridge, but it has some significant performance issues - and several browsers (Chrome and IE, I think) don't always have Java by default.

Have you checked the Flash support in Linux?  That's the only platform that it might be interesting to pick up.

**Comment by nfroidure** [comment]
For the Flash support it appears that it's a complete MIDI synth (a great peace of work https://github.com/keim/SiON/tree/master/src/org/si/sion/midi !) so it could be used to create a default MIDIOutput.

On my Debian Squeeze desktop with the default Flash player it works like a charm in Chrome. Kung Fu Fighting sounds particularly well :) http://mididb.com/kung-fu-fighting/.

Some files i opened are failing but i think it's due to the embedded MIDI file parser so it doesn't matter for us.

**Comment by nfroidure** [comment]
Another interesting related project https://github.com/keithwhor/audiosynth/issues/1

**Comment by cwilso** [comment]
I don't intend to expand the support with Flash or Java; if someone else wants to do this, please reopen this and take it, but my main goal is pushing forward native Web MIDI implementations.
