### ISSUE TITLE
Not receiving any sustain pedal message

### ISSUE THREAD

**Issue by jaycliff** [cwilso/WebMIDIAPIShim#35]
I made a small script to listen to midi inputs (similar to the one found in tests/multi.html) and found out that it doesn't seem to listen to any sustain pedal messages. The regular notes are working fine though. This could be a potential bug in the Jazz plugin, or I'm just a horrible coder :)

**Comment by notator** [comment]
I have no problem getting control messages from Jazz, and can't see where Jazz might treat the pedal message differently from any other. So the problem is probably yours. :-)
Or could it be that your output device/instrument doesn't support them?

**Comment by jaycliff** [comment]
Thanks James, I was actually using this Vanillin midi keyboard (www.vanilin.org/software/midikb.html‎). Turns out that this software doesn't send a real sustain pedal message (it just doesn't send a note off message when the 'pedal' is on).
