### ISSUE TITLE
Crasher using Chrome / Mac OS

### ISSUE THREAD

**Issue by j-funk** [cwilso/WebMIDIAPIShim#36]
1. go to chrome://flags/#enable-web-midi and enable 
2. restart browser
3. go to http://cwilso.github.io/WebMIDIAPIShim/tests/index.html
4. click button

Chrome Crash!

Here's the crash report:  http://pastebin.com/PYeJAWkt

**Comment by cwilso** [comment]
That seems like a bad install of the plugin?  It's not crashing anywhere near the shim.
