### ISSUE TITLE
sysex Uint8Array.length = 0 error

### ISSUE THREAD

**Issue by bjornm** [cwilso/WebMIDIAPIShim#40]
The sysex buffer code throws an error:

TypeError: Cannot set property length of #<Uint8Array> which has only a getter
    at MIDIInput._midiProc (.../WebMIDIAPI.js:306:42)

This is the code:

if (isSysexMessage || this._inLongSysexMessage) {
    evt.data = new Uint8Array( this._sysexBuffer );
    this._sysexBuffer.length = 0;
    this._inLongSysexMessage = false;
}

How about changing the third line to:

this._sysexBuffer = new Uint8Array(0);

**Comment by cwilso** [comment]
Fixed by submitted PR.

**Comment by bjornm** [comment]
Thanks!
