### ISSUE TITLE
Need to update to match current spec/Chrome implementation

### ISSUE THREAD

**Issue by tringenbach** [cwilso/WebMIDIAPIShim#41]
I tried to follow the example to play middle C:

``` javascript
var output = midiAccess.outputs.entries[indexOfPort];
```

But outputs seems to be a function and that code didn't work, and I ended up doing:

``` javascript
var output = midiAccess.outputs()[indexOfPort];
```

That worked, but it seems like that doesn't follow the spec.
I suspect inputs is the same way, but I haven't gotten that far yet.

**Comment by cwilso** [comment]
Yep, I haven't updated the shim yet to the latest standard.

**Comment by tringenbach** [comment]
Ah ok.  I wasn't sure. I looked at the December and Nov drafts and they both looked the same in that regard.

Is there a certain version of the standard that is implemented? That will help me write code that works now, and I can update it as the shim updates.

Is updating to the latest standard something you expect to do/have time for is the near term? If not I might consider trying to my hand at it and submitting a patch. (Or are you expecting major changes in the draft soon, in which case it's probably better to wait anyway)

Thanks.

**Comment by cwilso** [comment]
Well, it's close to what the Chrome implementation looks like currently.
 The draft is not planned to change much; I'll probably update the shim
when Chrome ships its updates to match the spec (in a month or so).

**Comment by abudaan** [comment]
I have updated my [fork](https://github.com/abudaan/WebMIDIAPIShim) of the shim to the latest W3C draft. 

I have updated/fixed all tests as well and I made a wrapper for the older WebMIDI implementation in Chromium.

Will send a pull request later today.

**Comment by mscuthbert** [comment]
I believe this has been fixed? Is the issue closed?

**Comment by cwilso** [comment]
oops!  Yes.
