### ISSUE TITLE
Splitting MIDI messages

### ISSUE THREAD

**Issue by jazz-soft** [cwilso/WebMIDIAPIShim#51]
Noticed the problem with the Channel Aftertouch message:
MIDI standard defines it as 2-byte message, e.g. [0xd0, 0x20],
but on some systems (Windows) it can be 3 bytes, e.g. [0xd0, 0x20, 0x00].
Shim reports that as two messages: [0xd0, 0x20], [0x00],
while it would better either report a 3-byte message or ignore the third byte.

**Comment by cwilso** [comment]
Dammit, Windows.  :)
