### ISSUE TITLE
Jazz Plugin crashes on requestMidiAccess

### ISSUE THREAD

**Issue by rikner** [cwilso/WebMIDIAPIShim#59]
I just tested the update from Jan 15, 2015 with my web app and the Jazz plugin 1.4 on Mac OSX Yosemite.

Before the update, requestMidiAccess() based on the shim and the Jazz plugin worked without problems. When activating the chrome flag for web midi, the native implementation was used. I just had to differentiate between the input-iterator (native) and the input-array (shim) in my code. So everything was fine.

Now with the update, the native web midi still works fine with my code, but if turn native web midi off and try to run requestMidiAccess() with the shim, the jazz-plugin crashes immediately with following error:

> [Error] Error: Error calling method on NPObject.
>   MidiInInfo (WebMIDIAPI.js, line 270)
>   MIDIInput (WebMIDIAPI.js, line 270)
>   _createMIDIPortMap (WebMIDIAPI.js, line 212)
>   _onReady (WebMIDIAPI.js, line 190)
>   (anonyme Funktion) ([native code], line 0)

I can restart the plugin and reload the page, but the next time I try to do requestMidiAccess() it fails again.

This happened to me in all three browsers (Chrome, Firefox, Safari). I re-installed the Jazz plugin but it didn't solve the problem. So is this some kind if compatibility problem with the OSX version of the Jazz plugin?

**Comment by rikner** [comment]
I also discovered this problem on Windows. Maybe it's an issue with Chrome. Since I'm really not sure yet, where the problem is, I will close this issue.

**Comment by turtec** [comment]
I got the same error while using the virtual piano "Midi Keys" at line 1236 : info = instance.MidiInInfo(name);

If i use a "real" midikeyboard everything works fine.

**Comment by jazz-soft** [comment]
Sascha, what is the virtual piano "Midi Keys"? Can you please give a link? Would like to test...

**Comment by turtec** [comment]
Hi,

here is the link: 

http://www.manyetas.com/creed/midikeys.html http://www.manyetas.com/creed/midikeys.html

i am using these tool for some testing purposes. 

Greetings 

Sascha
