### ISSUE TITLE
Problems getting sysex access

### ISSUE THREAD

**Issue by gritd** [cwilso/WebMIDIAPIShim#65]
Sorry but I just can't seem to get a sysex permission on the webMIDI:

navigator.requestMIDIAccess({sysex:true}).<...>
throws a "An attempt was made to break through the security policy of the user agent."

however, I have enable the full midi control in chrome's settings. Is there anything else I need to do? Or does this only work from https?

**Comment by AndrewHollis** [comment]
From my understanding this needs https to work.

You can host on github as https.

**Comment by cwilso** [comment]
Yes, you need https for sysex.  (Note this is coming from Chrome's native implementation, not the shim - the shim doesn't check for secure origin.
