### ISSUE TITLE
Platform dependent initialization failed.

### ISSUE THREAD

**Issue by carraragiovanni** [cwilso/WebMIDIAPIShim#73]
[In this example](http://cwilso.github.io/WebMIDIAPIShim/examples/list_devices/) and in my own implementation using Chrome, I am getting the error: `Platform dependent initialization failed.` 

I feel like it may be this same error that was seen before in chromium: https://bugs.chromium.org/p/chromium/issues/detail?id=718140 

Any idea what's going on here?

**Comment by cwilso** [comment]
Hmm, no.  What OS and browser version are you using?

**Comment by carraragiovanni** [comment]
OSX 10.13.1
Chrome latest (62.0.3202.94)

Seems to happen to my friend and me with any MIDI supported website, for example this one: http://nicroto.github.io/viktor/

Thanks!!

**Comment by carraragiovanni** [comment]
@cwilso Going to close this issue because it only happens intermittently. 

I'm developing [tunelark](https://www.tunelark.com/) and our MIDI sometime breaks, but every time it's broken, any other website using MIDI input also breaks. The other day it was working in Canary but not in Chrome which I thought was noteworthy. 

Thanks!! Giovanni

**Comment by toyoshim** [comment]
I guess you saw Chrome's native Web MIDI errors. We noticed experimentally launched new code seemed to hit a Core MIDI bug, and quickly turned down the experiments.

**Comment by carraragiovanni** [comment]
@toyoshim Thanks for the info!!
