### ISSUE TITLE
Add sounds to play music

### ISSUE THREAD

**Issue by surikov** [cwilso/WebMIDIAPIShim#77]
Add sampled instruments to play music

Examples (about 2000 instruments and drums, full MIDI set)
https://surikov.github.io/webaudiofont/examples/dynamic.html
or
https://surikov.github.io/midi-sounds-react-examples/examples/midi-sounds-example10/build/

**Comment by cwilso** [comment]
Although I'm happy to point people to such features, I REALLY do not want this polyfill to expand to install effectively a soft synth.
